@startuml
title Drone Rescue Mission

actor CommandCenter as "Command Center"
participant Explorer as "Explorer"
participant NavigationSystem as "Navigation System"
participant Radar as "Radar"
participant Coordinates as "Coordinates"
participant Scanner as "Scanner"
participant Tracker as "Tracker"


CommandCenter -> Explorer: Initiate Rescue Mission
Explorer -> NavigationSystem: Take Decision

loop until Land is Found
    NavigationSystem -> Radar: Travel to location
    NavigationSystem -> Coordinates: Update Coordinates
    Radar -> Radar: Check for land
    Radar -> NavigationSystem: Return results
end
NavigationSystem -> Explorer: Land found
Explorer --> NavigationSystem: Continue Exploration
loop until Points of Interest Found
    NavigationSystem -> Coordinates: Update Coordinates
    NavigationSystem -> Scanner: Check for Points of Interest
    Scanner --> NavigationSystem: Points of Interest found
    NavigationSystem -> Tracker: Track Points of Interest
    Tracker --> NavigationSystem: Points of Interest Tracked
end
Explorer -> CommandCenter: Return Closest Creek to Emergency Site
@enduml

